"""add_ailog_workflow_execution

Revision ID: 12995095ab81
Revises: 5a58ceb04e1c
Create Date: 2026-06-01 14:17:28.634831
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '12995095ab81'
down_revision: Union[str, None] = '5a58ceb04e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_source', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('execution_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_logs_execution_id'), ['execution_id'], unique=False)
        batch_op.create_foreign_key('fk_ai_logs_execution_id', 'executions', ['execution_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ai_logs_execution_id', type_='foreignkey')

        batch_op.drop_index(batch_op.f('ix_ai_logs_execution_id'))
        batch_op.drop_column('execution_id')
        batch_op.drop_column('workflow_source')

    # ### end Alembic commands ###

