"""add_step_executions

Revision ID: 5a58ceb04e1c
Revises: 20260601_0001
Create Date: 2026-06-01 13:41:46.475673
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5a58ceb04e1c'
down_revision: Union[str, None] = '20260601_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('step_executions',
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_executions_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_executions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_executions_step_id'), ['step_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('step_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_executions_step_id'))
        batch_op.drop_index(batch_op.f('ix_step_executions_status'))
        batch_op.drop_index(batch_op.f('ix_step_executions_execution_id'))

    op.drop_table('step_executions')
    # ### end Alembic commands ###

