"""add_ailog_fields

Revision ID: 603b36ebd39b
Revises: 12995095ab81
Create Date: 2026-06-01 15:05:58.428751
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '603b36ebd39b'
down_revision: Union[str, None] = '12995095ab81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('success', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.add_column(sa.Column('error_message', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_logs_workflow_id'), ['workflow_id'], unique=False)
        batch_op.create_foreign_key('fk_ai_logs_workflow_id', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ai_logs_workflow_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ai_logs_workflow_id'))
        batch_op.drop_column('error_message')
        batch_op.drop_column('success')
        batch_op.drop_column('workflow_id')

    # ### end Alembic commands ###

